export const VIEW_CONSTANTS = {
	HOME: 'HOME',
	LOGIN: 'LOGIN'
};

export const ACTION_CONSTANTS = {
	LOAD_HOME_VIEW: 'LOAD_HOME_VIEW',
	SHOW_LOADING: 'SHOW_LOADING'
};

export default {
	VIEW_CONSTANTS,
	ACTION_CONSTANTS
};
